spring.datasource.url=jdbc:mysql://192.168.33.10:3307/CRUDEtudiant?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true

server.port=8089